version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"
  pre_build:
    commands:
      - echo "Pre-build phase"
  build:
    commands:
      - echo "Start Maven build"
      - mvn clean package
  post_build:
    commands:
      - echo "Build finished, preparing artifacts"

artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/*
